name: SPFx CI CD

on:
  push:
    branches: ['\d+.x']
  pull_request:
    branches: ['\d+.x']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  packagePath: sharepoint/solution/LaserficheSharePointOnlineIntegration.sppkg
  packagePathUserDocs: UserDocuments

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{github.run_number}}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}

      - name: Install dependencies
        run: npm ci

      - name: Build solution
        run: gulp build

      - name: Bundle and package
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      - name: Upload Build Package
        uses: actions/upload-artifact@v3
        with:
          path: |
            ${{ env.packagePath }}
            ${{ env.packagePathUserDocs }}
